create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
create table building (id bigserial not null, address varchar(255), name varchar(255), primary key (id));
create table employee (id bigserial not null, email varchar(255) not null, name varchar(255), password varchar(255) not null, role varchar(255), surname varchar(255), office_building_id bigint, office_office_id varchar(255), primary key (id));
create table installation (id bigserial not null, date_of_installation timestamp(6), date_of_removal timestamp(6), office_building_id bigint, office_office_id varchar(255), sensor_id bigint, primary key (id));
create table office (building_id bigint not null, office_id varchar(255) not null, capacity integer not null, surface float(53) not null, primary key (building_id, office_id));
create table sensor (id bigserial not null, serial_num bigint, sensor_type_id bigint not null, primary key (id));
create table sensor_type (id bigserial not null, maximal float(53) not null, minimal float(53) not null, name smallint, optimal float(53) not null, primary key (id));
alter table if exists employee add constraint UK_fopic1oh5oln2khj8eat6ino0 unique (email);
alter table if exists employee add constraint FKtjc9mhw7auwot5u1e64q62ixq foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FKcuhtwho5qrpxdvv0uscr912u4 foreign key (office_building_id, office_office_id) references office;
alter table if exists installation add constraint FK1n7bstjlr15u40843dd8d4bhl foreign key (sensor_id) references sensor;
alter table if exists sensor add constraint FKkqk3ael7wsis75xbgkeiupfbp foreign key (sensor_type_id) references sensor_type;
